# Generated by Django 4.1.7 on 2023-03-04 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'ordering': ('-is_main', 'tag__name')},
        ),
    ]
