# Generated by Django 4.1.7 on 2023-03-04 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'ordering': ('name',), 'verbose_name': 'Учитель', 'verbose_name_plural': 'Учителя'},
        ),
    ]
